### ISSUE TITLE
[feature/register_family] 강아지네 등록 페이지 UI 구현

### ISSUE THREAD

**Issue by seuriseuljjeok** [meongmory/meongmory_android#19]
## Description
와이어프레임을 바탕으로 강아지네 등록 페이지 UI 구현

## To-do
- [x] 강아지네 추가 페이지
- [x] 초대코드 입력 페이지
- [x] 이름 입력 페이지
