### ISSUE TITLE
[feature/bottom] Bottom Navigation 3개 화면 초기셋팅

### ISSUE THREAD

**Issue by SsongSik** [meongmory/meongmory_android#28]
## Description
앱 메인화면의 3개 바텀네비게이션 탭과 3개 화면 설정

## To-do
- [x] MainActivity에서 BottomNavigation 설정
- [x] 3개의 화면 구성
- [x] BottomNavigation과 3개의 화면 연결 및 테스트
- [x] border 적용
