### ISSUE TITLE
[feature/picture] 사진 그리드 화면 구현

### ISSUE THREAD

**Issue by SsongSik** [meongmory/meongmory_android#47]
## Description
사진 그리드 화면 구현

## To-do
- [ ] 그리드 레이아웃 구현
- [ ] coil 라이브러리 추가
- [ ] 사진 post 구현
